CREATE DATABASE IF NOT EXISTS lab_mysql;
USE lab_mysql;
DROP TABLE IF EXISTS invoices;
DROP TABLE IF EXISTS salespersons;
DROP TABLE IF EXISTS cars;
DROP TABLE IF EXISTS customers;
CREATE TABLE IF NOT EXISTS `customers` (
	`Customer_ID` INTEGER NOT NULL AUTO_INCREMENT,
	`CustomerCode` VARCHAR(255) NOT NULL,
	`name` VARCHAR(255) NOT NULL,
	`phone_number` VARCHAR(255) NOT NULL,
	`email` VARCHAR(255) NOT NULL,
	`address` VARCHAR(255) NOT NULL,
	`city` VARCHAR(255) NOT NULL,
	`state_province` VARCHAR(255) NOT NULL,
	`country` VARCHAR(255) NOT NULL,
	`zip_postal_code` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`Customer_ID`)
);


CREATE TABLE IF NOT EXISTS `cars` (
	`Car_ID` INTEGER NOT NULL AUTO_INCREMENT,
	`vin` VARCHAR(255) NOT NULL UNIQUE,
	`manufacturer` VARCHAR(255) NOT NULL,
	`model` VARCHAR(255) NOT NULL,
	`year` YEAR NOT NULL,
	`color` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`Car_ID`)
);


CREATE TABLE IF NOT EXISTS `salespersons` (
	`Salesperson_ID` INTEGER NOT NULL AUTO_INCREMENT,
	`StaffCode` VARCHAR(255) NOT NULL,
	`name` VARCHAR(255) NOT NULL,
	`store` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`Salesperson_ID`)
);


CREATE TABLE IF NOT EXISTS `invoices` (
	`Invoice_ID` INTEGER NOT NULL AUTO_INCREMENT,
	`invoice_number` VARCHAR(255) NOT NULL UNIQUE,
	`invoice_date` DATE NOT NULL,
	`Car_ID` INTEGER NOT NULL,
	`Customer_ID` INTEGER NOT NULL,
	`Salesperson_ID` INTEGER NOT NULL,
	PRIMARY KEY(`Invoice_ID`)
);


ALTER TABLE `invoices`
ADD FOREIGN KEY(`Car_ID`) REFERENCES `cars`(`Car_ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `invoices`
ADD FOREIGN KEY(`Customer_ID`) REFERENCES `customers`(`Customer_ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `invoices`
ADD FOREIGN KEY(`Salesperson_ID`) REFERENCES `salespersons`(`Salesperson_ID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;